name: Auto Update Readme

on: 
  schedule: 
    - cron: "0 8 1 * *"
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  reqenv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update Readme
      run: |
        python ./updateNoInfo.py
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add *.md
        git commit -m '自动更新园区楼栋信息'
        git push origin master
